services:
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/${POSTGRES_DB}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_DISABLE_REGISTRATION=true
      - NEXT_PUBLIC_CREDENTIALS_ENABLED=false
    restart: always
    # build: . # uncomment to build from source
    image: ghcr.io/linkwarden/linkwarden:${TAG} # comment to build from source
    volumes:
      - linkwarden_data:/data/data
    networks:
      - linkwarden
      - traefik
      - postgres
    depends_on:
      - meilisearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.koshaq.net`)"
      - "traefik.http.routers.linkwarden.entrypoints=websecure"
      - "traefik.http.routers.linkwarden.tls.certresolver=letsencrypt"
      - "traefik.http.routers.linkwarden.middlewares=hsts-header@docker,compress@docker"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.linkwarden-compress.compress=true"
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    volumes:
      - meili_data:/meili_data
    networks:
      - linkwarden
    security_opt:
      - no-new-privileges:true
networks:
  linkwarden:
    internal: true
  postgres:
    external: true
  traefik:
    external: true
volumes:
  linkwarden_data:
  meili_data:
